Adopt Freestyle::Usage
cardstack/boxel-archive-2021 pull request #251
Opened 2021-01-18 22:01 UTC by mattmcmanus

CS-53

2021-01-19 09:32 UTC, lukemelia commented
This appears to break the `Source` output. It may be that we have to bake this into freestyle in order to fix that.

![Screen Shot 2021-01-19 at 5 31 56 PM](https://user-images.githubusercontent.com/353/105015214-454c3980-5a7c-11eb-9f78-1213bd07dab9.png)

2021-01-19 09:51 UTC, lukemelia requested changes

2021-01-19 09:51 UTC, lukemelia commented on app/components/boxel/breadcrumbs/usage.hbs
> -</FreestyleUsage>
I think it is useful to show a "manually" constructed version, in case someone needs to do it. Is the ComponentUsage API conducive to showing more than one example?

2021-01-19 09:51 UTC, lukemelia commented on app/components/doc/component-usage/args/index.hbs
> +    Yield=(component 'doc/component-usage/argument' type="Yield")
Seems like we also need `Object`, `Date`, `Component`, `Array` in order to cover know use cases in this repo (including open PRs).

2021-01-19 09:51 UTC, lukemelia commented on app/components/doc/component-usage/argument/index.hbs
> +</div>
+1 to a table or grid.

2021-01-19 09:51 UTC, lukemelia commented on app/components/doc/component-usage/argument/index.hbs
> +      (concat "ComponentUsageArgument__controls--" @type)
It is cool that Argument accepts a block so that you could provide a custom UI for a particular situation.

2021-01-19 09:51 UTC, lukemelia commented on app/components/doc/component-usage/string/index.js
> +    }
Fine for now, but I'm not crazy about this UI solution.

2021-01-19 09:51 UTC, lukemelia commented on app/styles/components/component-usage.css
> +.ComponentUsage {
BEM naming would be `component-usage` IIRC

2021-01-19 09:52 UTC, lukemelia commented
a row hover state on the argument entries would be a nice touch, to make it easier to eye-track from the component to the UI widget.

2021-01-19 16:14 UTC, mattmcmanus commented on app/components/boxel/breadcrumbs/usage.hbs
> -</FreestyleUsage>
Right now we can just call ComponentUsage again

2021-01-19 16:21 UTC, mattmcmanus commented on app/components/doc/component-usage/string/index.js
> +    }
Added details to a subtask on the Linear issue: https://linear.app/cardstack/issue/CS-53/improve-component-documentation-by-declaring-arguments

2021-01-28 06:14 UTC, lukemelia commented
![boxel](https://user-images.githubusercontent.com/353/106097885-0badb980-6173-11eb-817f-3775364a9c46.png)

2021-01-28 15:10 UTC, burieberry approved these changes
This is great

2021-01-28 17:48 UTC, merged