Thread components and Card Pay groundwork
cardstack/boxel-archive-2021 pull request #252
Opened 2021-01-18 23:38 UTC by burieberry

- Added card-pay route with 3 threads
- Can click through the first scenario to see message animation
- Thread modal container and its contextual components: Header, Content, Sidebar, Sidebar::Section, SidebarCard container
- Refactor of thread components and documentation: Milestones, Participant, ParticipantList, ParticipantsBox, ProgressBox, Message...

CS-94

<img width="1122" alt="scenario" src="https://user-images.githubusercontent.com/16160806/104970871-fbe7e580-59ba-11eb-8923-5bac455262c4.png">

<img width="1190" alt="thread-message" src="https://user-images.githubusercontent.com/16160806/104971246-28e8c800-59bc-11eb-9003-adddd85db429.png">

<img width="834" alt="milestones" src="https://user-images.githubusercontent.com/16160806/104971206-0a82cc80-59bc-11eb-9e19-a12d12b4e494.png">

<img width="950" alt="thread-participants-box" src="https://user-images.githubusercontent.com/16160806/104971216-11a9da80-59bc-11eb-809a-440873ee795a.png">

<img width="857" alt="thread-progress-box" src="https://user-images.githubusercontent.com/16160806/104971222-17072500-59bc-11eb-8119-131b081bb619.png">

2021-01-19 09:18 UTC, lukemelia requested changes
Looking great! I left a smattering of questions and thoughts.

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/milestones/index.hbs
> +    <li class="milestones__item {{if (gt @completedCount i) "completed"}} {{if (eq @completedCount i) "current"}}">
consider using a `{{#let (gt @completedCount i) as |isComplete|}} ... {{/let}}` in order to reduce duplication of `(gt @completedCount i)` and improve readability.

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/participant-list/usage.hbs
> +    <li><code>@hasLogo</code> (boolean) — Defaults to false.</li>
I don't think `hasLogo` belongs here.

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/participant-list/usage.js
> +];
Perhaps this sample data should include a participant with an organization, since that affects the `hasLogo` flag.

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/participant/index.hbs
> +<div class="participant {{if @hasLogo "participant__has-logo"}} {{unless @title "participant--icon-only"}}" ...attributes>
After merging, consider refactoring with `cn` helper from ember-class-names-helper.

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/participant/usage.hbs
> +    <li><code>@image</code> (url string) — Defaults to generic profile icon.</li>
Should we include `@hasLogo` here?

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/thread/index.hbs
> +  </Workflow::Container> --}}
Is there a reason to keep this commented code around?

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/thread/message/index.js
> +      }
Nice! ✨

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/thread/taskbar.hbs
> +    <div class="cardflow__taskbar-count">{{@activeTasks.length}} {{#if (eq @activeTasks.length 1)}}task{{else}}tasks{{/if}} for this workflow</div>
Consider bringing in [ember-inflector](https://github.com/emberjs/ember-inflector) to use `pluralize` helper for this. We could wait until we have other examples too if this is the only one.

2021-01-19 09:18 UTC, lukemelia commented on app/components/cardflow.hbs
> +    {{!-- TODO: Extract component - Reply to message box --}}
Let's be sure to capture this in AirTable

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/thread/progress-box/index.hbs
> +</Boxel::Thread::SidebarCard>
If Boxel::ProgressBox will always be used with both the circle and the milestones and there are not varying needs to customize the circle or milestones, then there is no benefit to using contextual components here. We can just pass in the needed args and pass them along to the child components and present a simpler API.

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/milestones/index.hbs
> +</ul>
On my computer, the border on the incomplete milestones looks "interrupted". Is that by design?

![image](https://user-images.githubusercontent.com/353/105011759-48452b00-5a78-11eb-91a7-e056a2a353ec.png)

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/progress-circle/index.js
> +  @tracked size = this.args.size ? this.args.size : 120;
This results in a one-time assignment to size rather than allowing it to update dynamically (e.g. in the usage.hbs). Instead, use:

```js
get size() {
  return this.args.size || 120;
}
```

or, if we are willing to take a dependency on the excellent [macro-decorators library](https://github.com/pzuraq/macro-decorators):

```js
  @reads('args.size', 120) size;
```

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/thread/index.hbs
> +</section>
I think the newer named blocks API would be a better fit here than contextual components since it really isn't up to the consuming developer to compose these components together. Matt or I can help if you haven't used named blocks yet.

2021-01-19 09:18 UTC, lukemelia commented on app/components/boxel/thread/participants-box/usage.hbs
> +    <li><code>@groupClass</code> (string) — CSS class name for a group of participants.</li>
I don't see `groupClass` used anywhere

2021-01-19 09:21 UTC, lukemelia commented
On a smaller browser width, the CardPay workflow card's "Full screen/Collapse" button doesn't actually do anything. Maybe it should be hidden below the threshold where it is functional?

2021-01-19 23:05 UTC, burieberry commented on app/components/boxel/milestones/index.hbs
> +    <li class="milestones__item {{if (gt @completedCount i) "completed"}} {{if (eq @completedCount i) "current"}}">
Done

2021-01-19 23:05 UTC, burieberry commented on app/components/boxel/thread/index.hbs
> +  </Workflow::Container> --}}
Done

2021-01-19 23:06 UTC, burieberry commented on app/components/boxel/thread/taskbar.hbs
> +    <div class="cardflow__taskbar-count">{{@activeTasks.length}} {{#if (eq @activeTasks.length 1)}}task{{else}}tasks{{/if}} for this workflow</div>
It is also needed for collection items count. I can do on a later PR.

2021-01-19 23:09 UTC, burieberry commented on app/components/boxel/thread/progress-box/index.hbs
> +</Boxel::Thread::SidebarCard>
WIP. I'll move some of the logic here, so that user doesn't have to pass in both `@completedCount` and `@percentComplete`.

2021-01-19 23:09 UTC, burieberry commented on app/components/boxel/milestones/index.hbs
> +</ul>
Argh Safari. This should be fixed now.

2021-01-19 23:13 UTC, burieberry commented on app/components/boxel/progress-circle/index.js
> +  @tracked size = this.args.size ? this.args.size : 120;
`macro-decorators` library looks great but when I try to do `import { reads } from 'macro-decorators';` the module is not found. Am I missing something? I tried installing it in `devDependencies`, then removed and tried in `dependencies`, but didn't help. Currently it's not installed.

2021-01-19 23:14 UTC, burieberry commented on app/components/boxel/thread/participants-box/usage.hbs
> +    <li><code>@groupClass</code> (string) — CSS class name for a group of participants.</li>
Removed. No longer necessary since using `hasLogo` arg.

2021-01-20 05:42 UTC, lukemelia commented on app/components/boxel/thread/taskbar.hbs
> +    <div class="cardflow__taskbar-count">{{@activeTasks.length}} {{#if (eq @activeTasks.length 1)}}task{{else}}tasks{{/if}} for this workflow</div>
👍

2021-01-20 05:44 UTC, lukemelia commented on app/components/boxel/thread/progress-box/index.hbs
> +</Boxel::Thread::SidebarCard>
👍

2021-01-20 06:46 UTC, lukemelia commented on app/components/boxel/progress-circle/index.js
> +  @tracked size = this.args.size ? this.args.size : 120;
I opened a PR against this branch with it added: https://github.com/cardstack/boxel/pull/254 -- needed ember-auto-import which is not mentioned anywhere in the docs.

2021-01-21 00:39 UTC, burieberry commented on app/components/boxel/thread/index.hbs
> +</section>
Received this build error when trying to try named blocks: `Assertion Failed: Named blocks are not currently available` Upgrading the ember version doesn't seem to be enough.

2021-01-21 04:09 UTC, lukemelia commented on app/components/boxel/thread/index.hbs
> +</section>
It is only available natively in 3.25. We'll need the ember-named-blocks-polyfill. I'll prep a branch with it today.

2021-01-21 14:00 UTC, lukemelia commented on app/components/boxel/thread/index.hbs
> +</section>
I verified that #255 (against master) works with named blocks

2021-01-21 23:25 UTC, lukemelia commented on app/components/boxel/participant-list/index.hbs
> +    {{#if (lt i this.maxCount)}}
the [`take`](https://github.com/DockYard/ember-composable-helpers#take) helper from ember-composable-helpers would be a nice way to express this.

2021-01-21 23:25 UTC, lukemelia commented on app/components/boxel/thread/modal.hbs
> +    </:sidebar>
Named Blocks look great 👍

2021-01-22 16:33 UTC, merged

2021-01-22 16:35 UTC, burieberry commented
Merged this branch into another branch that is a copy of the old master, to squash it down to 1 commit message. (It was hard to squash commits with various merges from the master)