Boxel::Menu component
cardstack/boxel-archive-2021 pull request #268
Opened 2021-02-03 19:24 UTC by lukemelia

- menu-item helper for expressive menu definition
- add ember-link addon dependency to make creating link menu items easy
- Extract Boxel::SortMenu component

Boxel::SortMenu:

![Screenshot 2021-02-02 at 7 01 06 PM](https://user-images.githubusercontent.com/353/106591451-3fc91600-6589-11eb-8fc6-fb8c8ea95b74.png)

https://user-images.githubusercontent.com/353/106591458-422b7000-6589-11eb-9e22-abc46d3bc4ec.mov

Boxel::Menu:

https://user-images.githubusercontent.com/353/106883283-c2350f80-671a-11eb-8e66-45de22d21f1f.mov

Boxel::DropdownButton:

![Screenshot 2021-02-04 at 6 55 00 PM](https://user-images.githubusercontent.com/353/106883310-c82af080-671a-11eb-8d6e-e2e63e79bcf4.png)

CS-142

2021-02-04 16:36 UTC, burieberry commented
@lukemelia Looks good but the scroll seems to be broken. Comparison with the current version:

https://user-images.githubusercontent.com/16160806/106924400-073a5100-66dd-11eb-94a7-d307c5d7750b.mp4

2021-02-04 18:56 UTC, lukemelia commented
> @lukemelia Looks good but the scroll seems to be broken. Comparison with the current version:

I'll take a look tomorrow

2021-02-08 07:53 UTC, lukemelia commented
I've addressed the SortMenu scrolling and made it better than the original. @mattmcmanus can you give this a review?

2021-02-08 15:06 UTC, mattmcmanus requested changes
Looks good to me. Just one request for clarification in the code.

2021-02-08 15:06 UTC, mattmcmanus commented on app/components/boxel/sort-menu/index.js
> +    if (maxHeightArg && maxHeightArg > 150) {
Can we make these consts with some clear names as to what they are?

2021-02-08 15:31 UTC, mattmcmanus commented
Also, are we OK with building on top of basic dropdown and wormhole? Should we consider something that may be a more better for the future? ie: popper.js?

2021-02-08 15:34 UTC, mattmcmanus commented
And it's higher level tool tippy.js: https://atomiks.github.io/tippyjs/

2021-02-08 17:14 UTC, lukemelia commented on app/components/boxel/sort-menu/index.js
> +    if (maxHeightArg && maxHeightArg > 150) {
✅

2021-02-08 17:15 UTC, lukemelia commented
> Also, are we OK with building on top of basic dropdown and wormhole? Should we consider something that may be a more better for the future? ie: popper.js?

I think that ember-basic-dropdown is a reliable primitive for the Ember community. When it is time to shift from wormhole, Miguel Camba will do it and have a migration path if necessary.

2021-02-08 23:57 UTC, burieberry approved these changes

2021-02-09 04:41 UTC, merged