Component tests for Button, SelectButton, Menu, SortMenu, SelectionControlGroup
cardstack/boxel-archive-2021 pull request #287
Opened 2021-02-23 10:33 UTC by Aierie

CS-255
CS-256
CS-257
CS-258
CS-259

Scaffolded todos for tests that I'm going to implement later. Would appreciate feedback @burieberry @lukemelia

2021-02-23 18:36 UTC, Aierie commented on addon/components/boxel/button/index.hbs
>    disabled={{@disabled}}
Made this commit after discussing with Burcu about the case where someone sets a different `disabled` attribute from the `@disabled` argument, and the attribute takes precedence. 
```js
<Boxel::Button @disabled={{false}} disabled={{true}}> Button text </Boxel::Button>
```


The button's styles would be misleading - a disabled button would look normal. With this change, we style directly based on the button's state so what you see is what you get.

@burieberry @lukemelia wondering about the role of the `@disabled` argument after this change? Is there much benefit in exposing `@disabled` now, if it's overwritable by the `disabled` attribute?

2021-02-23 18:56 UTC, Aierie commented on addon/components/boxel/button/index.hbs
>    disabled={{@disabled}}
Not sure how I found this, but apparently there is a use case for making buttons look disabled visually, behave disabled (via pointer events), but not actually have the disabled attribute: 

https://gomakethings.com/dont-disable-buttons-while-submitting-forms-with-ajax/

(mainly raised because it's interesting, don't think this is something we should make easy for users to do)

2021-02-24 09:24 UTC, lukemelia commented on tests/integration/components/boxel/selection-control-group-test.js
> + * Wondering why we don't toggleSelectAll on the Boxel::Button as well, if its text is select all
I've wondered this myself!

2021-02-24 09:24 UTC, lukemelia commented on tests/integration/components/boxel/selection-control-group-test.js
> + * It's a dependency of ember-power-select, so it's installed at the moment, I think we should probably specify it as a dependency explicitly so we don't accidentally break things.
Agreed

2021-02-24 09:24 UTC, lukemelia commented on tests/integration/components/boxel/sort-menu-test.js
> + * Are styles, like classes, merged?
No, they are not.

2021-02-24 17:52 UTC, burieberry commented on tests/integration/components/boxel/selection-control-group-test.js
> + * Wondering why we don't toggleSelectAll on the Boxel::Button as well, if its text is select all
Hmm here it's more likely that the `selection-control-group` is a `fieldset`, `select-button` is an `input` of type radio, the text is the label, and the '...' icon that appears is a button.

2021-02-25 09:10 UTC, Aierie commented on tests/integration/components/boxel/selection-control-group-test.js
> + * Wondering why we don't toggleSelectAll on the Boxel::Button as well, if its text is select all
We could implement it that way I guess! Right now it's a bit simpler:

https://github.com/cardstack/boxel/blob/3bca464569843b5e585873ab2aaaadde3d5746c0/addon/components/boxel/selection-control-group/index.hbs#L1-L28

2021-03-01 15:26 UTC, lukemelia requested changes
Looks good overall, except the issue I left comments about.

2021-03-01 15:26 UTC, lukemelia commented on tests/integration/components/boxel/button-test.js
> +    this.set('clicked', false);
This could be a simple JS variable. No need to use `set`. i.e. `let clicked = false;` and `clicked = true;` and `assert.ok(clicked);`

2021-03-01 15:26 UTC, lukemelia commented on tests/integration/components/boxel/menu-test.js
> +    this.set('lastClicked', null);
Same thing as above. Use simple JS locals here. If you're using a variable in hbs, you should use `set`, if only in JS, use a local.

2021-03-01 15:26 UTC, lukemelia commented on tests/integration/components/boxel/selection-control-group-test.js
> +        this.set('toggled', true);
make `toggled` a local and don't use `set`.

2021-03-01 18:07 UTC, Aierie commented
Agreed, thanks for spotting the issues with local variables @lukemelia!

2021-03-01 18:10 UTC, lukemelia approved these changes

2021-03-02 17:42 UTC, burieberry commented on tests/integration/components/boxel/button-test.js
> +const DROPDOWN_BUTTON_SELECTOR = '.boxel-dropdown-button';
@Aierie  My only suggestion is to use [ember-test-selectors](https://github.com/simplabs/ember-test-selectors) instead of class names. What this means is on the button component's hbs file you would add a `data-test` attribute, such as:

```<button class="boxel-button" data-test-boxel-button ...attributes> ... </button>```

Then when writing the test:
`assert.dom('[data-test-boxel-button]').exists();`

Makes life so much easier, and it means you don't have to worry if you ever have to change the class name in the component.

Here's an example from Cardhost:
- Component: https://github.com/cardstack/cardstack/blob/master/packages/cardhost/app/components/card-size-toggle.hbs
- Test: https://github.com/cardstack/cardstack/blob/master/packages/cardhost/tests/integration/components/card-size-toggle-test.js

2021-03-02 17:47 UTC, Aierie commented on tests/integration/components/boxel/button-test.js
> +const DROPDOWN_BUTTON_SELECTOR = '.boxel-dropdown-button';
Ah that seems good! It's nice to have them removed in prod. Will implement that and then merge.

2021-03-03 09:02 UTC, merged