Add Boxel::Field and Boxel::Input components
cardstack/boxel-archive-2021 pull request #295
Opened 2021-03-04 01:14 UTC by burieberry

<img width="764" alt="field" src="https://user-images.githubusercontent.com/16160806/110048928-d4f13300-7d1e-11eb-9cfe-8df5352a1b63.png">

<img width="763" alt="input" src="https://user-images.githubusercontent.com/16160806/110048933-d884ba00-7d1e-11eb-8778-85ccc889f83b.png">

2021-03-08 17:00 UTC, lukemelia requested changes
General approach looks great. Left a few questions/suggestions.

2021-03-08 17:00 UTC, lukemelia commented on addon/components/boxel/input/index.css
> +/* TODO: required and disabled styles */
What's the status of these?

2021-03-08 17:00 UTC, lukemelia commented on addon/components/boxel/input/index.css
> +  border-radius: 5px;
Consider using ` --boxel-border-radius-sm`

2021-03-08 17:00 UTC, lukemelia commented on addon/components/boxel/input/index.js
> +  @tracked value;
It doesn't look like this `value` is used by anything. The template using `@value`

2021-03-08 17:00 UTC, lukemelia commented on package.json
> +    "ember-css-element-queries": "^1.0.0",
This addon's repository has been archived (https://github.com/simplabs/ember-css-element-queries). Should we consider a different implementation?

2021-03-08 17:37 UTC, burieberry commented on package.json
> +    "ember-css-element-queries": "^1.0.0",
Yeah, I wonder why they archived it. Maybe `css-element-queries` (https://github.com/marcj/css-element-queries) now works for ember out-of-the-box. I was planning to try but forgot about it.

2021-03-08 22:57 UTC, burieberry commented on package.json
> +    "ember-css-element-queries": "^1.0.0",
Update on this: It didn't work out-of-the-box. There's this note on the readme (https://github.com/marcj/css-element-queries#module-loader), but I'm not sure where it needs to be added.

2021-03-08 23:03 UTC, burieberry commented
@lukemelia By the way, dependency lint started failing on the `ubuntu-latest` and `ember-beta` steps for all our PRs. We can add a config file for it, but it's strange that it's not failing for the other tests or that it just started failing.

2021-03-09 06:09 UTC, lukemelia commented on package.json
> +    "ember-css-element-queries": "^1.0.0",
I saw that you removed it. If you do want to use it, I'm happy to help figure out how to get the css-element-queries module to work.

2021-03-09 06:13 UTC, lukemelia commented on addon/components/boxel/input/index.hbs
> +  @value={{this.value}}
Why don't we want to just rely on data-down/actions-up for this and require @onInput to update the passed in @value?

2021-03-10 00:43 UTC, burieberry commented on package.json
> +    "ember-css-element-queries": "^1.0.0",
Ok we can make a separate ticket for this

2021-03-10 00:45 UTC, burieberry commented on addon/components/boxel/input/index.hbs
> +  @value={{this.value}}
Yes, that was the whole point. I got tired.

2021-03-10 10:45 UTC, lukemelia approved these changes

2021-03-10 16:09 UTC, burieberry commented
@lukemelia FYI, I don't know if you've seen it but I've also added a TextField component which is a pre-packaged version of Boxel::Field wrapper with text type Boxel::Input. I'm thinking of doing the same for other form field types. If having that wrapper Field component doesn't work out or if it becomes unnecessary we can go back to not doing it that way.

2021-03-10 16:12 UTC, burieberry commented
Ah also I'll double check the disabled etc state styling with Gardella during design review, just so that I don't delay merging this any longer.

2021-03-10 16:17 UTC, merged