Org landing page
cardstack/boxel-archive-2021 pull request #312
Opened 2021-03-24 11:20 UTC by Aierie

2021-03-25 14:41 UTC, burieberry requested changes
Looks good. Made a couple small comments. We should also get the styling for smaller viewports. That can be a follow-up PR if you want to merge this in first.

2021-03-25 14:41 UTC, burieberry commented on tests/dummy/app/templates/cardstack/index.hbs
> +      {{!-- @kind={{if this.edges.darkTheme "secondary-dark" "secondary-light"}} --}}
You can remove the commented out code on this template

2021-03-25 14:41 UTC, burieberry commented on public/images/icons/card-catalog-logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 70 70">
Don't forget to pass the images through ImageOptim. Cleans them up and reduces files sizes nicely.

2021-03-25 14:41 UTC, burieberry commented on tests/dummy/app/templates/cardstack/index.hbs
> +      {{!-- @kind={{if this.edges.darkTheme "secondary-dark" "secondary-light"}} --}}
Also since we don't need the `darkTheme` stuff anymore, you can remove it from the edges service. It was annoying to have it there anyway. You can remove the test for that, too.

2021-03-25 14:53 UTC, Aierie commented on tests/dummy/app/templates/cardstack/index.hbs
> +      {{!-- @kind={{if this.edges.darkTheme "secondary-dark" "secondary-light"}} --}}
Oops. Thanks for catching that one. Will do!

2021-03-25 14:53 UTC, Aierie commented on public/images/icons/card-catalog-logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 70 70">
Yep, I did optimize the svgs. I kept `xmlns` because we need it if we're using svgs in a way besides inline, which I did here via `img`. I used `img` because the svgs here don't exactly need to be svgs, they could be any other image type in the future, and it's easier to replace images if all we need to do is replace a url.

2021-03-25 15:16 UTC, Aierie commented
> Looks good. Made a couple small comments. We should also get the styling for smaller viewports. That can be a follow-up PR if you want to merge this in first.

re: merging first, I feel like this is better merged after #315, so in the meantime will talk to design about how they would like it to look on smaller screens.

2021-03-25 17:32 UTC, burieberry approved these changes

2021-03-25 20:36 UTC, burieberry reviewed
I was about to fix the conflict and merge this, but noticed a couple of things we can do to make the layout more flexible.

2021-03-25 20:36 UTC, burieberry commented on tests/dummy/app/css/templates/cardstack.css
> +  padding-bottom: 9.375rem;
We can make the layout more flexible even without designs for smaller screens. I'd add a `padding: var(--boxel-sp-lg)` instead of the padding-bottom here. And then add `margin-bottom: var(--boxel-sp-lg);` to each of its immediate children.

2021-03-25 20:36 UTC, burieberry commented on tests/dummy/app/css/templates/cardstack.css
> +  margin: var(--boxel-sp-lg) 0;
Since the padding will take care of the top spacing, this can just be `margin-bottom: var(--boxel-sp-lg);`

2021-03-25 20:36 UTC, burieberry commented on tests/dummy/app/css/templates/cardstack.css
> +  height: 18.75rem;
Make this `min-height` instead of a fixed height, so that when the page shrinks, the text content doesn't get cropped, and something like a `padding: var(--boxel-sp);` so that the container maintains some spacing between its boundary and the content.

2021-03-26 08:30 UTC, Aierie commented
@burieberry I've applied changes to tidy up the layout. There's many ways we can polish this, but I think we can refine that when we go through review from the design team, since a lot of things are still in flux.

2021-03-26 08:30 UTC, merged