Input field optional and error states styling
cardstack/boxel-archive-2021 pull request #369
Opened 2021-05-27 22:12 UTC by burieberry

CS-497

Adds @helperText, @errorMessage, @optional args to Boxel::Input component and their styling

<img width="902" alt="required-field" src="https://user-images.githubusercontent.com/16160806/119903582-e65d6c00-bf16-11eb-88d7-f1ad18fa14ef.png">

2021-05-31 11:19 UTC, Aierie requested changes

2021-05-31 11:19 UTC, Aierie commented on addon/components/boxel/input/index.hbs
> +  <div id="helper-text" class="boxel-input__helper-text">{{@helperText}}</div>
Using multiple inputs means that we have multiple elements with the id 'helper-text' on the same page if they all have helper text. If we want to use aria-describedby, we need to enforce unique ids for each input's helper text. Same for elements with the id error-message. 

One way of doing this could be assigning a unique ID on a per-component basis, and appending that to 'helper-text' and 'error-message'?

2021-05-31 11:19 UTC, Aierie commented on addon/components/boxel/input/usage.hbs
> +      @errorMessage={{this.errorMessage}}
`@required` adds the `required` html attribute, but doesn't prevent users from submitting stuff unless we add an action similar to `this.validate` for every component that uses this input, or use the input within a form. It also doesn't add any error messages unless it's specified by the parent. I would expect a `@required` argument to do one of the above, but I don't think it does without some help at the moment.

2021-05-31 11:19 UTC, Aierie commented on addon/components/boxel/input/usage.hbs
> +      @errorMessage={{this.errorMessage}}
The main value the `@required` argument adds is preventing the `@optional` label from being shown. Is preventing footguns like supplying both `required` and `optional` the job of the user and not this component? If so, would it be better to simply supply `required` via a html attribute?

Before committing to argument or attribute, would like to understand a bit more about the "Optional" label: 
1. Do we always show the "Optional" label when a field is not required?
2. Is the text "Optional" is the only thing we will use that label for? Or will we do something like "Only for merchants"? Is a string argument better here?

2021-05-31 11:19 UTC, Aierie commented on addon/components/boxel/input/usage.hbs
> +      @errorMessage={{this.errorMessage}}
Also would want to control whether the error message shows via a separate toggle, eg. `@invalid`. Otherwise, all components that validate inputs will have to replace error messages with falsey values until they actually want to show them.

2021-06-01 17:39 UTC, burieberry commented on addon/components/boxel/input/usage.hbs
> +      @errorMessage={{this.errorMessage}}
I think it's fine for now to leave it up to the user whether they want to show the `Optional` label. There are cases where the field is optional but we don't want to display the optional label, a search field for example. Also I think it's fine to leave it up to the user what they want their error validation logic to be. It'll be different for different types of input field.

I started out with separate args for @invalid and @errorMessage, but then decided that to be redundant. The @errorMessage is falsey by default, and if an entry is deemed invalid, there should be a message explaining why.

I like the idea of making the optional field label a string field.

2021-06-01 18:06 UTC, Aierie commented on addon/components/boxel/input/usage.hbs
> +      @errorMessage={{this.errorMessage}}
Always showing a useful error message is nice! I'm for having `@invalid`  because it makes it easier to control when to show an error message, instead of having to assign falsey values to validation errors until they need to be shown, if we use getters to show them.

```
<Boxel::Input
  @value={{this.value1}}
  @errorMessage={{this.errorMessage1}}
/>
<Boxel::Input
  @value={{this.value2}}
  @errorMessage={{this.errorMessage2}}
/>

/* In component */
export default class Something extends Component {
  @tracked value1 = "";
  @tracked value2 = "";
  @tracked showErrors = false;

  get errorMessage1(){
    if (!this.showErrors) return ''
    if (this.value1.length < 20) return 'Answer is too short'
  }

  get errorMessage2(){
    if (!this.showErrors) return ''
    if (this.value2.length < 60) return 'Answer is too short'
  }
}
```

If we have `@invalid`, this becomes

```
<Boxel::Input
  @value={{this.value1}}
  @errorMessage={{this.errorMessage1}}
  @invalid={{this.showErrors}}
/>
<Boxel::Input
  @value={{this.value2}}
  @errorMessage={{this.errorMessage2}}
  @invalid={{this.showErrors}}
/>

/* In component */
export default class Something extends Component {
  @tracked value1 = "";
  @tracked value2 = "";
  @tracked showErrors = false;

  get errorMessage1(){
    if (this.value1.length < 20) return 'Answer is too short'
  }

  get errorMessage2(){
    if (this.value2.length < 60) return 'Answer is too short'
  }
}
```

2021-06-01 22:43 UTC, burieberry commented
Decided to keep the `@optional` label as is, any explanation can be done in the `@helperText` field. Added `@id` arg to aria fields for `@helperText` and `@errorMessage`. Passing `@invalid` as a separate arg.

2021-06-02 07:34 UTC, Aierie commented
Rebased to fix failing CI.

2021-06-02 08:17 UTC, Aierie commented
Do you know what happens if this input is wrapped in a label, and the helper, error text, and the optional label is shown? Does it get read as part of the label? @burieberry

2021-06-02 09:03 UTC, Aierie commented
Just realised this input seems to assume use within Boxel::Field - it uses grid positions that help for styling within the Boxel::Field component. This works for immediate use, but introduces unexpected behaviour when used within a grid for other things, and makes it dependent on Boxel::Field styling. 

Since helper and error text being included in a wrapping label is also an issue, I'm thinking we could:
1. Limit the responsibility of the Boxel::Input component. It controls the state - hover, focus, invalid. Wrapping components (eg. Boxel::Field) are responsible for ensuring an appropriate label, and display and placement of the error messages and helper text.
2. work towards this input component having a built-in label that displays itself like a Boxel::Field.

2021-06-02 15:23 UTC, Aierie approved these changes

2021-06-02 16:01 UTC, merged